name: latest_news
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
   
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  firebase_core: ^3.3.0
  go_router: ^14.1.3
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  carousel_slider: ^5.0.0
  webview_flutter: ^4.8.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  riff_switch: ^0.0.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
  #       
  #
flutter_intl:
  enabled: true
